manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joshyeram                            # <--- add this
      url-base: https://github.com/joshyeram    # <--- and this
  projects:
    - name: zmk
      remote: joshyeram
      revision: removeUSBpowercheck
      import: app/west.yml
  self:
    path: config